apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-feed
  name: udagram-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-feed
  template:
    metadata:
      labels:
        service: udagram-feed
    spec:
      containers:
        - image: ziademad/udagram-feed
          name: udagram-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: POSTGRESS_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_USERNAME

            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST

      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
